services:
  
  
  browser-interface:
  
    build:
      context: ./browser-interface
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - shared_volume:/shared
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://0.0.0.0:8000/ || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 5s
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    
  
  speech-to-text:

    build:
      context: ./speech-to-text
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    depends_on:
      - web-interface
    command: sh -c "python stt_server.py"


  locall-llm:

    build:
      context: ./local-llm
      dockerfile: Dockerfile
    #ports:
      #- "8000:8000"


  text-to-speech:

    build:
      context: ./text-to-speech
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared

  
volumes:
  shared_volume:  

