services:
  
  
  browser-interface:
  
    build:
      context: ./browser-interface
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - shared_volume:/shared
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://0.0.0.0:8000/ || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: sh -c "python /app/manage.py runserver 0.0.0.0:8000"


  speech-to-text:

    build:
      context: ./speech-to-text
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    depends_on:
      - browser-interface
    command: sh -c "python /app/stt_server.py"

    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


volumes:
  shared_volume:  

