services:
  
  
  browser-interface:
  
    build:
      context: ./browser-interface
    ports:
      - "8000:8000"
    volumes:
      - shared_volume:/shared
    command: sh -c "python /app/manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://0.0.0.0:8000/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s


  speech-to-text:

    build:
      context: ./speech-to-text
    volumes:
      - shared_volume:/shared
    depends_on:
      - browser-interface
    command: sh -c "python /app/stt_server.py"
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s


  local-llm:

    build:
      context: ./local-llm
    depends_on:
      - speech-to-text



  text-to-speech:

    build:
      context: ./text-to-speech
    volumes:
      - shared_volume:/shared
    depends_on:
      - local-llm
    command: sh -c "python /app/tts_server.py"
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s



volumes:
  shared_volume:  

